package org.gorpipe.compat;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Reads and writes committed baseline outputs.
 *
 * Baselines live beside the corpus rather than inside the generated case files so
 * that regenerating the case list never rewrites an output, and accepting a
 * behaviour change never rewrites a query.
 */
public final class BaselineStore {

    private static final String HEADER =
            "# GOR compatibility baselines. Generated by :compat:accept — do not hand-edit.";
    private static final String BEGIN = ">>> ";
    private static final String END = "<<<";

    private BaselineStore() {
    }

    public static Path pathFor(CompatCase c) {
        return CaseLoader.moduleRoot()
                .resolve("baselines")
                .resolve(c.category())
                .resolve(c.feature() + ".out");
    }

    /** The recorded form of a result: serialised output, or the error message. */
    public static String render(CompatResult r) {
        return r.failed() ? "ERROR: " + r.errorMessage + "\n" : r.serialised();
    }

    public static String load(CompatCase c) {
        Path file = pathFor(c);
        if (!Files.exists(file)) {
            return null;
        }
        return parse(file).get(c.id);
    }

    public static Map<String, String> loadAll(Path baselinesDir) {
        Map<String, String> all = new TreeMap<>();
        if (!Files.isDirectory(baselinesDir)) {
            return all;
        }
        try (Stream<Path> walk = Files.walk(baselinesDir)) {
            List<Path> files = walk.filter(p -> p.toString().endsWith(".out"))
                    .sorted().collect(Collectors.toList());
            for (Path f : files) {
                all.putAll(parse(f));
            }
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot enumerate baselines under " + baselinesDir, e);
        }
        return all;
    }

    public static void write(Path file, Map<String, String> idToOutput) {
        StringBuilder sb = new StringBuilder();
        sb.append(HEADER).append('\n');
        // Sorted so that a regenerated file differs only where behaviour differs.
        for (Map.Entry<String, String> e : new TreeMap<>(idToOutput).entrySet()) {
            sb.append(BEGIN).append(e.getKey()).append('\n');
            sb.append(e.getValue());
            if (!e.getValue().endsWith("\n")) {
                sb.append('\n');
            }
            sb.append(END).append('\n');
        }
        try {
            if (file.getParent() != null) {
                Files.createDirectories(file.getParent());
            }
            Files.writeString(file, sb.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot write baseline file " + file, e);
        }
    }

    private static Map<String, String> parse(Path file) {
        Map<String, String> result = new TreeMap<>();
        try {
            List<String> lines = Files.readAllLines(file, StandardCharsets.UTF_8);
            String currentId = null;
            StringBuilder body = new StringBuilder();
            for (String line : lines) {
                if (line.startsWith(BEGIN)) {
                    currentId = line.substring(BEGIN.length()).trim();
                    body.setLength(0);
                } else if (line.equals(END)) {
                    if (currentId == null) {
                        throw new IllegalStateException(
                                "Baseline file " + file + " has a closing marker with no case id");
                    }
                    result.put(currentId, body.toString());
                    currentId = null;
                } else if (currentId != null) {
                    body.append(line).append('\n');
                }
            }
            if (currentId != null) {
                throw new IllegalStateException(
                        "Baseline file " + file + " ends inside case '" + currentId + "'");
            }
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot read baseline file " + file, e);
        }
        return result;
    }
}
