package org.gorpipe.compat;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Deterministic fixtures, generated by this module rather than read from
 * tests/data, so that :compat stays independent of the unit test data submodule.
 */
public final class Fixtures {

    /**
     * Synthetic reference sequences. Short, fixed, and chosen so that an expected
     * base is easy to derive by hand: chr1 is ACGT repeated, chr2 is TTGCA
     * repeated.
     */
    private static final Map<String, String> SEQUENCES = new LinkedHashMap<>();

    static {
        SEQUENCES.put("chr1", "ACGT".repeat(250));
        SEQUENCES.put("chr2", "TTGCA".repeat(200));
    }

    private Fixtures() {
    }

    public static String referenceSequence(String chrom) {
        String seq = SEQUENCES.get(chrom);
        if (seq == null) {
            throw new IllegalArgumentException("No synthetic sequence for " + chrom);
        }
        return seq;
    }

    /**
     * Writes a chromSeq reference build under root and returns the config path.
     *
     * Layout is documented in scripts/refbuild/README.md: one file per contig
     * holding raw bases at one byte per base with no newlines, so that the byte at
     * offset pos-1 is the base at 1-based position pos.
     *
     * buildsize.gor and buildsplit.txt MUST NOT have a header line — gor's parser
     * reads them as bare pairs, and a header yields
     * NumberFormatException: For input string: "Size".
     */
    public static Path writeReferenceBuild(Path root) {
        try {
            Path chromSeq = root.resolve("chromSeq");
            Files.createDirectories(chromSeq);

            StringBuilder sizes = new StringBuilder();
            StringBuilder splits = new StringBuilder();

            for (Map.Entry<String, String> e : SEQUENCES.entrySet()) {
                String chrom = e.getKey();
                String seq = e.getValue();
                Files.writeString(chromSeq.resolve(chrom + ".txt"), seq, StandardCharsets.UTF_8);
                sizes.append(chrom).append('\t').append(seq.length()).append('\n');
                splits.append(chrom).append('\t').append(seq.length() / 2).append('\n');
            }

            Path sizeFile = root.resolve("buildsize.gor");
            Path splitFile = root.resolve("buildsplit.txt");
            Files.writeString(sizeFile, sizes.toString(), StandardCharsets.UTF_8);
            Files.writeString(splitFile, splits.toString(), StandardCharsets.UTF_8);

            Path config = root.resolve("gor_config.txt");
            String configBody = ""
                    + "buildPath\t" + chromSeq.toAbsolutePath() + "\n"
                    + "buildSizeFile\t" + sizeFile.toAbsolutePath() + "\n"
                    + "buildSplitFile\t" + splitFile.toAbsolutePath() + "\n";
            Files.writeString(config, configBody, StandardCharsets.UTF_8);

            return config;
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot write reference build under " + root, e);
        }
    }

    public static Path configFileIfPresent(Path root) {
        Path config = root.resolve("gor_config.txt");
        return Files.exists(config) ? config : null;
    }

    /** The shared fixture set that generated cases attach to their queries. */
    public static List<CompatInput> canonicalInputs() {
        List<CompatInput> inputs = new ArrayList<>();
        inputs.add(input("left.gor",
                "Chrom\tPos\tRef\tAlt\n"
                        + "chr1\t100\tA\tG\n"
                        + "chr1\t200\tC\tT\n"
                        + "chr2\t150\tG\tA\n"));
        inputs.add(input("right.gor",
                "Chrom\tPos\tGene\n"
                        + "chr1\t100\tBRCA1\n"
                        + "chr1\t250\tTP53\n"
                        + "chr2\t150\tEGFR\n"));
        inputs.add(input("segments.gor",
                "Chrom\tbpStart\tbpStop\tName\n"
                        + "chr1\t50\t150\tregionA\n"
                        + "chr1\t180\t260\tregionB\n"
                        + "chr2\t100\t200\tregionC\n"));
        inputs.add(input("pheno.tsv",
                "PN\tSex\tAge\n"
                        + "PN001\tM\t42\n"
                        + "PN002\tF\t37\n"));
        return inputs;
    }

    private static CompatInput input(String path, String content) {
        CompatInput in = new CompatInput();
        in.path = path;
        in.content = content;
        return in;
    }

    /** Reads a shared fixture from compat/data by relative path. */
    public static String readSharedData(String name, String caseId) {
        if (name == null) {
            throw new IllegalStateException("Case " + caseId
                    + " declares an input with neither content nor contentFile");
        }
        Path path = CaseLoader.moduleRoot().resolve("data").resolve(name);
        try {
            return Files.readString(path, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(
                    "Missing shared fixture " + path + " referenced by case " + caseId, e);
        }
    }
}
