package org.gorpipe.compat;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Deterministic fixtures, generated by this module rather than read from
 * tests/data, so that :compat stays independent of the unit test data submodule.
 */
public final class Fixtures {

    /**
     * Synthetic reference sequences. Short, fixed, and chosen so that an expected
     * base is easy to derive by hand: chr1 is ACGT repeated, chr2 is TTGCA
     * repeated.
     */
    private static final Map<String, String> SEQUENCES = new LinkedHashMap<>();

    static {
        SEQUENCES.put("chr1", "ACGT".repeat(250));
        SEQUENCES.put("chr2", "TTGCA".repeat(200));
    }

    private Fixtures() {
    }

    public static String referenceSequence(String chrom) {
        String seq = SEQUENCES.get(chrom);
        if (seq == null) {
            throw new IllegalArgumentException("No synthetic sequence for " + chrom);
        }
        return seq;
    }

    /**
     * Writes a chromSeq reference build under root and returns the config path.
     *
     * Layout is documented in scripts/refbuild/README.md: one file per contig
     * holding raw bases at one byte per base with no newlines, so that the byte at
     * offset pos-1 is the base at 1-based position pos.
     *
     * buildsize.gor and buildsplit.txt MUST NOT have a header line — gor's parser
     * reads them as bare pairs, and a header yields
     * NumberFormatException: For input string: "Size".
     */
    public static Path writeReferenceBuild(Path root) {
        try {
            Path chromSeq = root.resolve("chromSeq");
            Files.createDirectories(chromSeq);

            StringBuilder sizes = new StringBuilder();
            StringBuilder splits = new StringBuilder();

            for (Map.Entry<String, String> e : SEQUENCES.entrySet()) {
                String chrom = e.getKey();
                String seq = e.getValue();
                Files.writeString(chromSeq.resolve(chrom + ".txt"), seq, StandardCharsets.UTF_8);
                sizes.append(chrom).append('\t').append(seq.length()).append('\n');
                splits.append(chrom).append('\t').append(seq.length() / 2).append('\n');
            }

            Path sizeFile = root.resolve("buildsize.gor");
            Path splitFile = root.resolve("buildsplit.txt");
            Files.writeString(sizeFile, sizes.toString(), StandardCharsets.UTF_8);
            Files.writeString(splitFile, splits.toString(), StandardCharsets.UTF_8);

            Path config = root.resolve("gor_config.txt");
            String configBody = ""
                    + "buildPath\t" + chromSeq.toAbsolutePath() + "\n"
                    + "buildSizeFile\t" + sizeFile.toAbsolutePath() + "\n"
                    + "buildSplitFile\t" + splitFile.toAbsolutePath() + "\n";
            Files.writeString(config, configBody, StandardCharsets.UTF_8);

            return config;
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot write reference build under " + root, e);
        }
    }

    public static Path configFileIfPresent(Path root) {
        Path config = root.resolve("gor_config.txt");
        return Files.exists(config) ? config : null;
    }

    /** The shared fixture set that generated cases attach to their queries. */
    public static List<CompatInput> canonicalInputs() {
        List<CompatInput> inputs = new ArrayList<>();
        inputs.add(input("left.gor",
                "Chrom\tPos\tRef\tAlt\n"
                        + "chr1\t100\tA\tG\n"
                        + "chr1\t200\tC\tT\n"
                        + "chr2\t150\tG\tA\n"));
        inputs.add(input("right.gor",
                "Chrom\tPos\tGene\n"
                        + "chr1\t100\tBRCA1\n"
                        + "chr1\t250\tTP53\n"
                        + "chr2\t150\tEGFR\n"));
        inputs.add(input("segments.gor",
                "Chrom\tbpStart\tbpStop\tName\n"
                        + "chr1\t50\t150\tregionA\n"
                        + "chr1\t180\t260\tregionB\n"
                        + "chr2\t100\t200\tregionC\n"));
        // SAM-shaped, for the commands that read a CIGAR or Flag column
        // (BASES, CIGARSEGS, VARIANTS, BAMFLAG). Without it those commands could
        // only ever fail on their input shape.
        // Column names match what the commands look up: CIGAR, Flag, SEQ, QUAL.
        // SEQ and QUAL are the same length as the CIGAR's read-consuming ops, so a
        // case fails on the flag under test rather than on inconsistent input.
        // PILEUP looks up iSize, Seq, Flag, MapQ, Cigar, mrnm and mpos together,
        // so all seven are present rather than only the ones BASES needs.
        inputs.add(input("reads.gor",
                "Chrom\tPos\tFlag\tMAPQ\tCIGAR\tSEQ\tQUAL\tiSize\tmrnm\tmpos\n"
                        + "chr1\t100\t0\t60\t4M\tACGT\tIIII\t0\t=\t140\n"
                        + "chr1\t200\t16\t60\t2M1D2M\tACGT\tIIII\t0\t=\t240\n"
                        + "chr2\t150\t0\t60\t3M\tTTG\tIII\t0\t=\t190\n"));
        // Horizontally bucketed genotypes, for the tag-bucket commands (CSVSEL,
        // CSVCC, KING, QUEEN and friends). They look up "bucket" and "values"
        // columns by name; values holds one element per tag in the bucket, in the
        // order the tags appear in the relation below.
        // The af column is there for KING and KING2, which look it up by name.
        inputs.add(input("buckets.gor",
                "Chrom\tPos\tbucket\tvalues\taf\n"
                        + "chr1\t100\tb1\t0,1,2\t0.1\n"
                        + "chr1\t200\tb1\t1,1,0\t0.2\n"
                        + "chr2\t150\tb1\t2,0,1\t0.3\n"));
        // The tag-to-bucket relation: exactly two columns, distinct tags, and the
        // position of a tag within its bucket fixes the order of the values above.
        inputs.add(input("tagbuckets.tsv",
                "#PN\tbucket\n"
                        + "PN001\tb1\n"
                        + "PN002\tb1\n"
                        + "PN003\tb1\n"));
        // A tag selection: exactly one column of distinct tag ids.
        inputs.add(input("tagsel.tsv", "#PN\nPN001\nPN003\n"));
        // A second, disjoint selection, for the commands taking two tag lists.
        inputs.add(input("tagsel2.tsv", "#PN\nPN002\n"));
        // Per-sample genotypes, for the commands reading pn and gt columns rather
        // than a bucketed stream (GTGEN, PEDPIVOT).
        inputs.add(input("genotypes.gor",
                "Chrom\tPos\tPN\tGT\n"
                        + "chr1\t100\tPN001\t0/1\n"
                        + "chr1\t100\tPN002\t1/1\n"
                        + "chr1\t200\tPN001\t0/0\n"));
        // Per-sample coverage segments, which GTGEN takes as its second source.
        inputs.add(input("coverage.gor",
                "Chrom\tbpStart\tbpStop\tPN\n"
                        + "chr1\t50\t150\tPN001\n"
                        + "chr1\t50\t150\tPN002\n"
                        + "chr1\t150\t250\tPN001\n"));
        // A bucketed stream that also carries Ref and Alt, which GTTRANSPOSE
        // requires of its input.
        inputs.add(input("markerbuckets.gor",
                "Chrom\tPos\tRef\tAlt\tbucket\tvalues\taf\n"
                        + "chr1\t100\tA\tG\tb1\t0,1,2\t0.1\n"
                        + "chr1\t200\tC\tT\tb1\t1,1,0\t0.2\n"));
        // A marker source for GTTRANSPOSE's third argument.
        inputs.add(input("markers.gor",
                "Chrom\tPos\tRef\tAlt\n"
                        + "chr1\t100\tA\tG\n"
                        + "chr1\t200\tC\tT\n"));
        // A pedigree, for PEDPIVOT's second argument.
        inputs.add(input("pedigree.tsv",
                "#PN\tfather\tmother\n"
                        + "PN001\tPN002\tPN003\n"));
        // Tag pairs, which KING2 requires as (PN1, PN2) rather than a tag list.
        inputs.add(input("tagpairs.tsv", "#PN1\tPN2\nPN001\tPN002\n"));
        // Case-control status per tag, which CSVCC requires as (tag, cc-status).
        inputs.add(input("pheno-cc.tsv",
                "#PN\tcc\n"
                        + "PN001\t1\n"
                        + "PN002\t2\n"
                        + "PN003\t1\n"));
        // Variants whose Ref column agrees with the synthetic reference build, so
        // a command that checks a variant against the reference has something that
        // actually verifies. The bases are derived from the sequences above: chr1
        // is ACGT repeated, so position 100 is T; chr2 is TTGCA repeated, so
        // position 150 is A.
        inputs.add(input("refvariants.gor",
                "Chrom\tPos\tRef\tAlt\n"
                        + "chr1\t1\tA\tG\n"
                        + "chr1\t100\tT\tC\n"
                        + "chr2\t150\tA\tG\n"));
        // GAVA resolves gene, pos, ref, alt, pn, callcopies, phase and score by
        // name, and falls back to fixed positions for any it cannot find. Naming
        // all eight keeps the case exercising the analysis rather than the
        // fallback.
        inputs.add(input("gavavariants.gor",
                "Chrom\tbpStart\tbpStop\tgene_symbol\tPos\tRef\tAlt\tPN"
                        + "\tCallCopies\tPhase\tScore\n"
                        + "chr1\t50\t250\tBRCA1\t100\tA\tG\tPN001\t1\t0\t1.0\n"
                        + "chr1\t50\t250\tBRCA1\t200\tC\tT\tPN002\t2\t0\t2.0\n"
                        + "chr2\t100\t200\tEGFR\t150\tG\tA\tPN001\t1\t0\t1.5\n"));
        // For the statistics commands that need a p-value column (ADJUST).
        inputs.add(input("pvalues.gor",
                "Chrom\tPos\tPVal\n"
                        + "chr1\t100\t0.001\n"
                        + "chr1\t200\t0.04\n"
                        + "chr2\t150\t0.6\n"));
        inputs.add(input("pheno.tsv",
                "PN\tSex\tAge\n"
                        + "PN001\tM\t42\n"
                        + "PN002\tF\t37\n"));
        return inputs;
    }

    private static CompatInput input(String path, String content) {
        CompatInput in = new CompatInput();
        in.path = path;
        in.content = content;
        return in;
    }

    /** Reads a shared fixture from compat/data by relative path. */
    public static String readSharedData(String name, String caseId) {
        if (name == null) {
            throw new IllegalStateException("Case " + caseId
                    + " declares an input with neither content nor contentFile");
        }
        Path path = CaseLoader.moduleRoot().resolve("data").resolve(name);
        try {
            return Files.readString(path, StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(
                    "Missing shared fixture " + path + " referenced by case " + caseId, e);
        }
    }
}
