name: Build

on: [push]
#on: workflow_dispatch

env:
  INTEGRATION_TESTS_SECRETS_ENV: ${{ secrets.INTEGRATION_TESTS_SECRETS_ENV }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v4
      - name: Prepare env
        run: |
          echo ${INTEGRATION_TESTS_SECRETS_ENV} | base64 -d > tests/config/secrets.env
      - name: Build with Gradle
        run: |
          ./gradlew --no-daemon assemble

