name: Java CI

on: [push]

jobs:
  build:
    if: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew installDist -Pinclude.documentation
    - name: Publish package
      run: ./gradlew publish -PpublishToGithub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
