name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew installDist -Pinclude.documentation
      - name: Publish snapshot package
        if: ${{ github.ref == 'refs/heads/githubtest' }}
        run: ./gradlew publish -PpublishToGithub -Pversion=$(cat VERSION)-SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish release package
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: ./gradlew publish -PpublishToGithub -Pversion=$(cat VERSION)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
